apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-consumer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: "{{ .Values.consumer.image.repository }}:{{ .Values.consumer.image.tag }}"
          env:
            - name: NATS_URL
              value: "{{ .Values.consumer.env.NATS_URL }}"
          ports:
            - containerPort: {{ .Values.consumer.service.port }}
