apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.nats.service.type }}
  ports:
    - port: {{ .Values.nats.service.port }}
      targetPort: {{ .Values.nats.service.port }}
  selector:
    app: nats
