apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nats
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: "{{ .Values.nats.image }}:{{ .Values.nats.tag }}"
          ports:
            - containerPort: {{ .Values.nats.service.port }}
