apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-producer
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.producer.service.type }}
  ports:
    - port: {{ .Values.producer.service.port }}
      targetPort: {{ .Values.producer.service.port }}
  selector:
    app: producer
